#![no_std]
use soroban_sdk::{contract, contracterror, contractimpl, symbol_short, Bytes, Env, Symbol};
use ultrahonk_soroban_verifier::{UltraHonkVerifier, PROOF_BYTES};

/// Crown & Shadows ZK Verifier Contract
///
/// Stores a Verification Key (VK) generated from the Noir circuit and
/// exposes a `verify_proof` endpoint so the game backend can prove
/// a Knight guess is valid without revealing the hidden card.
#[contract]
pub struct CrownShadowsVerifier;

#[contracterror]
#[repr(u32)]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum Error {
    VkParseError = 1,
    ProofParseError = 2,
    VerificationFailed = 3,
    VkNotSet = 4,
}

#[contractimpl]
impl CrownShadowsVerifier {
    fn key_vk() -> Symbol {
        symbol_short!("vk")
    }

    /// Initialize the contract with the Verification Key generated
    /// from: `bb write_vk -b ./target/crown_shadows_circuits.json -o ./vk --scheme ultra_honk`
    pub fn __constructor(env: Env, vk_bytes: Bytes) -> Result<(), Error> {
        env.storage().instance().set(&Self::key_vk(), &vk_bytes);
        Ok(())
    }

    /// Verify an UltraHonk proof for a Knight guess.
    ///
    /// public_inputs encodes:
    ///   - card_commitment : Field (32 bytes)
    ///   - declared_guess  : Field (32 bytes)
    ///
    /// proof_bytes is generated by:
    ///   `bb prove -b ./target/crown_shadows_circuits.json -w ./target/witness.gz -o ./proof --scheme ultra_honk`
    pub fn verify_proof(env: Env, public_inputs: Bytes, proof_bytes: Bytes) -> Result<(), Error> {
        if proof_bytes.len() as usize != PROOF_BYTES {
            return Err(Error::ProofParseError);
        }

        let vk_bytes: Bytes = env
            .storage()
            .instance()
            .get(&Self::key_vk())
            .ok_or(Error::VkNotSet)?;

        let verifier =
            UltraHonkVerifier::new(&env, &vk_bytes).map_err(|_| Error::VkParseError)?;

        verifier
            .verify(&proof_bytes, &public_inputs)
            .map_err(|_| Error::VerificationFailed)?;

        Ok(())
    }
}
