#!/usr/bin/env bash
# Crown & Shadows - On-Chain Proof Verification
#
# Reads the proof + public inputs from the circuit build output
# and calls verify_proof on the deployed Soroban contract.
#
# Usage:
#   chmod +x blockchain/scripts/verify_on_chain.sh
#   blockchain/scripts/verify_on_chain.sh

set -euo pipefail

CIRCUITS_DIR="$(cd "$(dirname "$0")/../circuits" && pwd)"
CONTRACTS_DIR="$(cd "$(dirname "$0")/../contracts" && pwd)"
PROOF_FILE="$CIRCUITS_DIR/target/proof"
CONTRACT_ID_FILE="$CONTRACTS_DIR/contract_id.txt"

echo ""
echo "======================================"
echo " Crown & Shadows :: On-Chain Verify"
echo "======================================"
echo ""

if [[ ! -f "$PROOF_FILE" ]]; then
  echo "Error: Proof file not found. Run build_zk.sh first."
  exit 1
fi

if [[ ! -f "$CONTRACT_ID_FILE" ]]; then
  echo "Error: Contract ID not found. Run deploy.sh first."
  exit 1
fi

CONTRACT_ID=$(cat "$CONTRACT_ID_FILE")
PROOF_HEX=$(xxd -p -c 9999 "$PROOF_FILE" | tr -d '\n')

# Public inputs file (generated by nargo execute) – card_commitment + declared_guess
PUBLIC_INPUTS_FILE="$CIRCUITS_DIR/target/public_inputs"
if [[ ! -f "$PUBLIC_INPUTS_FILE" ]]; then
  echo "Error: Public inputs file not found at $PUBLIC_INPUTS_FILE"
  exit 1
fi
PUBLIC_INPUTS_HEX=$(xxd -p -c 9999 "$PUBLIC_INPUTS_FILE" | tr -d '\n')

echo "Contract ID:   $CONTRACT_ID"
echo "Invoking verify_proof..."
echo ""

stellar contract invoke \
  --id "$CONTRACT_ID" \
  --source-account default \
  --network testnet \
  -- \
  verify_proof \
  --public_inputs "$PUBLIC_INPUTS_HEX" \
  --proof_bytes "$PROOF_HEX"

echo ""
echo "✓  Proof verified successfully on-chain!"
echo "======================================"
